global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pediatric_bff'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['bff:3000']

  - job_name: 'pediatric_ai_engine'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai-engine:8000']
